apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabflix-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fabflix-redis
  template:
    metadata:
      labels:
        app: fabflix-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        command: ["redis-server", "--appendonly", "yes"]
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: fabflix-redis
  ports:
  - port: 6379
    targetPort: 6379
