apiVersion: v1
kind: ConfigMap
metadata:
  name: redisson-config
data:
  redisson.yaml: |
    ---
    clusterServersConfig:
      nodeAddresses:
        - "redis://redis-cluster-0.redis-cluster:6379"
        - "redis://redis-cluster-1.redis-cluster:6379"
        - "redis://redis-cluster-2.redis-cluster:6379"
        - "redis://redis-cluster-3.redis-cluster:6379"
        - "redis://redis-cluster-4.redis-cluster:6379"
        - "redis://redis-cluster-5.redis-cluster:6379"
      connectTimeout: 10000
      timeout: 3000
      retryAttempts: 3
      retryInterval: 1500
      slaveConnectionPoolSize: 24
      masterConnectionPoolSize: 24
      slaveConnectionMinimumIdleSize: 5
      masterConnectionMinimumIdleSize: 5
      idleConnectionTimeout: 10000
      dnsMonitoringInterval: 5000
      scanInterval: 2000
    threads: 16
    nettyThreads: 32
    codec: !<org.redisson.codec.MarshallingCodec> {}
    transportMode: "NIO"
